# Visit the url below for a reference of all configuration
# https://cloud.google.com/appengine/docs/python/config/appref

application: your-app-id  # The "Project ID" creted at https://console.cloud.google.com/iam-admin/projects
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  ENABLED_MODULES:
    modules.pages.pages
    modules.gallery.gallery
    modules.home.home

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"

handlers:
- url: /static/(.*)
  upload: static/(.*)
  static_files: static/\1
- url: /modules/([^/]*)/static/(.*)
  upload: modules/([^/]*)/static/(.*)
  static_files: modules/\1/static/\2
- url: /.*
  script: base.wsgi.app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
